# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Niroz Jung Karki
email: karkinirozjung@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 A Father, Husband, Yogi, Minimalist, Cyclist, Wanderer, Farmer, Software Engineer and a Technology Enthusiast.
#baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://nirozjung.github.io" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: nirozjung
github_username:  nirozjung
facebook_username: nirozjung
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://www.linkedin.com/in/nirozjung/

# Address information
#address_street: Arzloher-Straße 1 
#address_city: 
#address_state: 
#address_zip: 86529 Schrobenhausen

# Build settings
markdown: kramdown
